# Generated by Django 5.1.2 on 2024-10-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workevent',
            name='employee',
        ),
        migrations.AlterField(
            model_name='workevent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workevent',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
